version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: sistema
    #restart: always
    depends_on:
      - db-registro
    ports:
      - 8000:8000
    volumes: 
      - ./registro/:/app

  db-registro:
    image: mariadb
    container_name: registro-db
    #restart: always
    environment:
      MYSQL_DATABASE: registro
      MYSQL_USER: registro_user
      MYSQL_PASSWORD: "asjdghj"
      MYSQL_ROOT_PASSWORD: admin1234
    volumes:
      - db-registro:/var/lib/mysql
    ports:
      - 3320:3306

volumes:
  db:    
  db-registro:    

