# Generated by Django 4.0.2 on 2022-06-08 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('1', 'laptop'), ('2', 'cpu'), ('3', 'impresora'), ('4', 'todo en uno'), ('5', 'otros')], max_length=1, verbose_name='Tipo')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=100)),
                ('num_serie', models.CharField(max_length=100)),
                ('accesorios', models.CharField(max_length=200, verbose_name='Accesorios')),
                ('contra', models.CharField(max_length=100, verbose_name='Contraseña')),
                ('falla', models.CharField(max_length=100, verbose_name='Fallas')),
                ('extras', models.CharField(max_length=100, verbose_name='Extras')),
            ],
        ),
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('num_serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.dispositivo', verbose_name='Número de serie')),
            ],
        ),
    ]
